apiVersion: v1
kind: Service
metadata:
  name: externaldb
  namespace: learn-k8s-apiserver
spec:
  type: ExternalName
  externalName: db.local.testapp.private
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306